apiVersion: v1
kind: Service
metadata:
    name: back-end

spec:
    type: ClusterIP
    ports:
      - targetport: 80
        port: 80

    selector:
             app: myapp
             type: back-end
             

#kubectl create -f clusterip-service-definition.yaml
#kubectl get svc
#curl http://192.168.1.2:30008
