apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx


#kubectl create -f deployment-definition.yml
#kubectl get deployment
#kubectl get replicaset
#kubectl get pods
#kubectl create deployment --image=nginx nginx --dry-run=client -o yaml > nginx-deployment.yaml
#kubectl create -f nginx-deployment.yaml
#kubectl create deployment --image=nginx nginx --replicas=4 --dry-run=client -o yaml > nginx-deployment.yaml
