apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers: 
  - name: nginx
    image: nginx
    


#kubectl run nginx --image nginx
# kubectl apply -f pod.yaml
# kubectl get pods
#kubectl describe pod podname
#kubectl delete pod podname
